# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DErOr5S7fKE8hOU54-U94s88WvPay-Ad
"""

print("hello")